const Requstor = require("../../models/usersRequesters");
const cloudinary = require("cloudinary").v2;
const fs = require("fs");

const uuidv4 = require("uuid/v4");

cloudinary.config({
  cloud_name: process.env.clodinary_cloud_name || "",
  api_key: process.env.clodinary_api_key || "",
  api_secret: process.env.clodinary_api_secret || ""
});

exports.getposts = async (req, res) => {
  console.log("getting posts");

  Requstor.findOne({ _id: req.id })
    .then(doc => {
      res.json(doc.requests);
    })
    .catch(err => {
      console.log(err);
    });
};

exports.getallposts = (req, res) => {
  Requstor.find({ activeState: true })
    .then(docs => {
      var payload = [];

      docs.forEach(element => {
        payload.push(element.requests);
      });

      res.json(payload);
    })
    .catch(err => {
      console.log(err);
    });
};

exports.newpost = (req, res) => {
  console.log(req.body);
  console.log(req.id);
  console.log(req.files);

  console.log("new post");

  const postid = uuidv4();

  var promiseArr = [];

  req.files.forEach((element, index) => {
    console.log("path - " + element.path);
    promiseArr.push(fileupcloud(postid + "_" + index, element.path));
  });

  Promise.all(promiseArr)
    .then(result => {
      console.log(result);
      Requstor.findOneAndUpdate(
        { _id: req.id },
        {
          $push: {
            requests: {
              requestid: postid,
              title: req.body.title,
              description: req.body.description,
              estimatedBudget: req.body.estimatedBudget,
              donationTypeAccepted: req.body.donationTypeAccepted,
              createdAt: new Date().toISOString(), //timestamp
              images: result
            }
          }
        }
      )
        .then(doc => {
          console.log(doc);
          res.json({ msg: "success" });
        })
        .catch(err => {
          console.log(err);
        });
    })
    .catch(err => {
      console.log(err);
    });
};

const fileupcloud = function(filename, path) {
  console.log("cloud");
  return new Promise((resolve, reject) => {
    cloudinary.uploader.upload(
      path,
      {
        tags: "basic_sample",
        folder: "patron/",
        public_id: filename,
        sign_url: true
      },
      function(err, cvuploaddata) {
        console.log();
        console.log("** File Upload");
        if (err) {
          console.warn(err);
          reject(err);
        }
        console.log(
          "* public_id for the uploaded pdf is generated by Cloudinary's service."
        );
        console.log("* " + cvuploaddata.public_id);
        console.log("* " + cvuploaddata.url);

        var cvhttps =
          cvuploaddata.url.slice(0, 4) +
          "s:" +
          cvuploaddata.url.slice(5, cvuploaddata.url.length);

        resolve(cvhttps);

        fs.unlinkSync(path);
      }
    );
  });
};
